### ISSUE TITLE
Chatterbot

### ISSUE THREAD

**Issue by naranjarosa** [ShoneGK/ChatterPy#1]
I have installed the github package 'pip install git+https://github.com/ShoneGK/ChatterPy' and the python library 'pip install chatterbot-corpus' but it doesn't work. No chatterbot library recognizes me. I am using Python 3.11.0 on Windows 10. What could be the problem?

I've created a new folder, created a file called bot.py, opened it with Visual Studio Code, and pasted in the basic code usage:

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('Ron Obvious')

trainer = ChatterBotCorpusTrainer(chatbot)

trainer.train("chatterbot.corpus.english")

trainer.train("chatterbot.corpus.english.greetings")

trainer.train("chatterbot.corpus.english.conversations")

chatbot.get_response("Hello, how are you today?")

I save changes, and I try to run and I get this message in terminal:

PS C:\Users\danie\Desktop\Chatterbot> python bot.py
  File "C:\Users\danie\Desktop\Chatterbot\bot.py", line 1
    from chatterbot.trainers import ChatterBotCorpusTrainer
IndentationError: unexpected indent

I dont know what happens. Thank you!

**Comment by ShoneGK** [comment]
Looks like its not an issue with the library but a formatting error on your end

try copy-pasting this by pressing the copy button on the top right of the code block:

```python

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('Ron Obvious')

trainer = ChatterBotCorpusTrainer(chatbot)
trainer.train("chatterbot.corpus.english")
trainer.train("chatterbot.corpus.english.greetings")
trainer.train("chatterbot.corpus.english.conversations")

print(chatbot.get_response("Hello, how are you today?"))
```

make sure that you paste this in a fresh file with nothing in it.
If you have any more questions feel free to add another comment!
